[tool.poetry]
name = "pykka"
version = "4.0.1"
description = "Pykka is a Python implementation of the actor model"
authors = ["Stein Magnus Jodal <stein.magnus@jodal.no>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jodal/pykka"
repository = "https://github.com/jodal/pykka"
documentation = "https://pykka.readthedocs.io/"
keywords = ["actor", "concurrency", "threading"]
classifiers = [
   "Development Status :: 5 - Production/Stable",
   "Intended Audience :: Developers",
   "Topic :: Software Development :: Libraries",
]
include = ["docs", "examples", "tests"]

[tool.poetry.dependencies]
python = "^3.8.0"
typing-extensions = { version = "^4.0.0", python = "<3.10" }


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
